### ISSUE TITLE
HW: Part Details Missing

### ISSUE THREAD

**Issue by jowami** [dimka-rs/nrf52board#3]
We have some questiones regarding the BOM and the design on KiCAD.
1) What is the part number of D2, SW1, SW2, Q1
2) What is the color of D1,D3,D4
3) What is the full part of E73-2G4M04S . There are E73-2G4M04S1A, E73-2G4M04S1D，E73-2G4M04S1AX etc.

**Comment by dimka-rs** [comment]
Hi, @jowami 
1. D2: NSR1020MW2; SW1,2: no idea, some side tact switch I had; Q1: PMV65XP.
2. D1,3,4: LC191yct. I have them all yellow, but you can use any 0603 LED you like.
3. My part is marked 2G4M04S. it is old, I guess naming has changed since. It is NRF52832, so E73-2G4M04S1B looks best fit.

**Comment by jowami** [comment]
@dimka-rs Thanks, will submit the changes and send you a pull request

**Comment by dimka-rs** [comment]
@jowami you're welcome. I've already pushed some changes.

**Comment by jowami** [comment]
Thanks!

Could you please contact me on jwamicha@gmail.com

We have some work.

Thanks.

**Comment by dimka-rs** [comment]
@jowami I've found and bushed button name. It is SKSCLCE010, but 'PTS840 GMP SMTR LFS' and 'EVQ-P7K01P' should also fit.
